/**
 * This file is autogenerated by Scaffold-HBAR.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = {
  296: {
    AgentVaultFactory: {
      address: "0x0000000000000000000000000000000000000000",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "hbarUsdFeed_",
              type: "address",
              internalType: "contract AggregatorV3Interface",
            },
            {
              name: "defaultMaxPriceAge_",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "allVaults",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "createVault",
          inputs: [],
          outputs: [
            {
              name: "vault",
              type: "address",
              internalType: "contract AgentVault",
            },
          ],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "defaultMaxPriceAge",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "hbarUsdFeed",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract AggregatorV3Interface",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "vaultCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "vaultsOf",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address[]",
              internalType: "address[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "event",
          name: "VaultCreated",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "vault",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "FundingFailed",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 0,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
