// Copies the AgentVault + AgentVaultFactory ABIs from Foundry build output into src/abi.ts.
// Run after changing the contracts: `yarn foundry:compile && yarn workspace @sh/agent sync-abi`.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "..", "foundry", "out");
const abiOf = name => JSON.parse(readFileSync(join(out, `${name}.sol`, `${name}.json`), "utf8")).abi;

const body = [
  "// Generated by scripts/sync-abi.mjs from packages/foundry/out. Do not edit by hand.",
  `export const agentVaultAbi = ${JSON.stringify(abiOf("AgentVault"), null, 2)} as const;`,
  `export const agentVaultFactoryAbi = ${JSON.stringify(abiOf("AgentVaultFactory"), null, 2)} as const;`,
  "",
].join("\n\n");

writeFileSync(join(here, "..", "src", "abi.ts"), body);
console.log("Wrote src/abi.ts");
